#include "stdafx.h"
#include "TokenizerConstants.h"

#include <assert.h>

const bool kTokenIsUnary[kNumberOfTokens] =
{
	// kTokenEndOfFile = 0,
	false,
	// kTokenEndOfFunction,
	false,
	// kTokenOperatorPlus,               
	false,
	// kTokenOperatorMinus,              
	false,
	// kTokenOperatorMultiplication,     
	false,
	// kTokenOperatorDivision,           
	false,
	// kTokenOperatorModulo,             
	false,
	// kTokenOperatorExponentiation,     
	false,
	// kTokenOperatorLog,                
	false,
	// kTokenOperatorEquality,           
	false,
	// kTokenOperatorApproximatellyEqual,
	false,
	// kTokenOperatorSmaller,            
	false,
	// kTokenOperatorSmallerOrEqual,     
	false,
	// kTokenOperatorGreater,           
	false,
	// kTokenOperatorGreaterOrEqual,     
	false,
	// kTokenOperatorNotEqual,           
	false,
	// kTokenOperatorLogicalAnd,        
	false,
	// kTokenOperatorLogicalOr,	    
	false,
	// kTokenOperatorLogicalNot,        
	true,
	// kTokenOperatorLogicalXOr,       
	false,
	// kTokenOperatorBinaryAnd,          
	false,
	// kTokenOperatorBinaryOr,           
	false,
	// kTokenOperatorBinaryNot,          
	true,
	// kTokenOperatorBinaryXOr,          
	false,
	// kTokenOperatorBitShiftLeft,      
	false,
	// kTokenOperatorBitShiftRight,     
	false,
	// kTokenOperatorBitCount,
	true,
	// kTokenOperatorPercentage,         
	false,
	// kTokenOperatorConditionalIf,      
	false,
	// kTokenOperatorConditionalThen,    
	false,
	// kTokenOperatorConditionalWhen,    
	false,
	// kTokenBracketOpen_1,              			
	false,
	// kTokenBracketOpen_2,              
	false,
	// kTokenBracketOpen_3,              
	false,
	// kTokenBracketClose_1,            
	false,
	// kTokenBracketClose_2,            
	false,
	// kTokenBracketClose_3,           
	false,
	// kTokenIdentifier,
	false,
	// kTokenNumber,
	false,
	// kTokenPocketCards,
	false,
	// kTokenDoubleShebang,
	false,
};

const bool kTokenIsBinary[kNumberOfTokens] =
{
	// kTokenEndOfFile = 0,
	false,
	// kTokenEndOfFunction,
	false,
	// kTokenOperatorPlus,               
	true,
	// kTokenOperatorMinus, 
	true,
	// kTokenOperatorMultiplication,     
	true,
	// kTokenOperatorDivision,           
	true,
	// kTokenOperatorModulo,             
	true,
	// kTokenOperatorExponentiation,     
	true,
	// kTokenOperatorLog,                
	true,
	// kTokenOperatorEquality,           
	true,
	// kTokenOperatorApproximatellyEqual,
	true,
	// kTokenOperatorSmaller,            
	true,
	// kTokenOperatorSmallerOrEqual,     
	true,
	// kTokenOperatorGreater,           
	true,
	// kTokenOperatorGreaterOrEqual,     
	true,
	// kTokenOperatorNotEqual,           
	true,
	// kTokenOperatorLogicalAnd,        
	true,
	// kTokenOperatorLogicalOr,	    
	true,
	// kTokenOperatorLogicalNot,        
	false,
	// kTokenOperatorLogicalXOr,       
	true,
	// kTokenOperatorBinaryAnd,          
	true,
	// kTokenOperatorBinaryOr,           
	true,
	// kTokenOperatorBinaryNot,          
	false,
	// kTokenOperatorBinaryXOr,          
	true,
	// kTokenOperatorBitShiftLeft,      
	true,
	// kTokenOperatorBitShiftRight,     
	true,
	// kTokenOperatorBitCount,
	false,
	// kTokenOperatorPercentage,         
	true,
	// kTokenOperatorConditionalIf,      
	false,
	// kTokenOperatorConditionalThen,    
	false,
	// kTokenOperatorConditionalWhen,    
	true, //??
	// kTokenBracketOpen_1,              			
	false,
	// kTokenBracketOpen_2,              
	false,
	// kTokenBracketOpen_3,              
	false,
	// kTokenBracketClose_1,            
	false,
	// kTokenBracketClose_2,            
	false,
	// kTokenBracketClose_3,           
	false,
	// kTokenIdentifier,
	false,
	// kTokenNumber,
	false,
	// kTokenPocketCards,
	false,
	// kTokenDoubleShebang,
	false,
};

bool TokenIsUnary(int token)
{
	assert(token >=0);
	assert(token < kNumberOfTokens);
	return kTokenIsUnary[token];
}

bool TokenIsBinary(int token)
{
	assert(token >=0);
	assert(token < kNumberOfTokens);
	return kTokenIsBinary[token];
}

/*
kTokenEndOfFile = 0,
	kTokenEndOfFunction,
	kTokenOperatorPlus,               
	kTokenOperatorMinus,              
	kTokenOperatorMultiplication,     
	kTokenOperatorDivision,           
	kTokenOperatorModulo,             
	kTokenOperatorExponentiation,     
	kTokenOperatorLog,                
	kTokenOperatorEquality,           
	kTokenOperatorApproximatellyEqual,
	kTokenOperatorSmaller,            
	kTokenOperatorSmallerOrEqual,     
	kTokenOperatorGreater,           
	kTokenOperatorGreaterOrEqual,     
	kTokenOperatorNotEqual,           
	kTokenOperatorLogicalAnd,        
	kTokenOperatorLogicalOr,	    
	kTokenOperatorLogicalNot,        
	kTokenOperatorLogicalXOr,       
	kTokenOperatorBinaryAnd,          
	kTokenOperatorBinaryOr,           
	kTokenOperatorBinaryNot,          
	kTokenOperatorBinaryXOr,          
	kTokenOperatorBitShiftLeft,      
	kTokenOperatorBitShiftRight,     
	kTokenOperatorPercentage,         
	kTokenOperatorConditionalIf,      
	kTokenOperatorConditionalThen,    
	kTokenOperatorConditionalWhen,    
	kTokenBracketOpen_1,              			
	kTokenBracketOpen_2,              
	kTokenBracketOpen_3,              
	kTokenBracketClose_1,            
	kTokenBracketClose_2,            
	kTokenBracketClose_3,           
	kTokenIdentifier,
	kTokenNumber,
	kTokenPocketCards,
	kTokenDoubleShebang,
	*/