#ifndef INC_SWAG_FUNCTION_FOR_OPENHOLDEM_2_1_X_H
#define INC_SWAG_FUNCTION_FOR_OPENHOLDEM_2_1_X_H


void AddSwagFunctionsForOH_2_1_x_IfExistent();

#endif INC_SWAG_FUNCTION_FOR_OPENHOLDEM_2_1_X_H