#ifndef XMLRPC_C_VERSION_INCLUDED 
#define XMLRPC_C_VERSION_INCLUDED 
/* generated by Windows/mkvers.bat on 05.04.2013 ... */ 
#define XMLRPC_C_VERSION "1.32.5" 
#define XMLRPC_VERSION_MAJOR 1 
#define XMLRPC_VERSION_MINOR 32 
#define XMLRPC_VERSION_POINT 5 
#endif 
